name: nst_tunnel
description: NST Tunnel desktop client — import and manage your own configs.
publish_to: 'none'
version: 2.21.0+1731

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true